### ISSUE TITLE
How can I reference the build parameters in a shell script?

### ISSUE THREAD

**Issue by kraftydevil** [nickgrealy/poll-mailbox-trigger#1]
For example, I wrote a ruby script that parses the email and neither of these allow me to pass the email's content:
ruby /usr/bin/emailParser.rb pmt_content
ruby /usr/bin/emailParser.rb $pmt_content
ruby /usr/bin/emailParser.rb ${pmt_content}

**Comment by nickgrealy** [comment]
Hi Gregory,

I just fired up Jenkins 1.626 (fresh install) on my mac, installed the Poll Mailbox Plugin 1.019, configured a job with "Execute Script" -> "echo $pmt_content", and it worked fine, I got the contents of an email printed to the job console.

Lets do some troubleshooting...
1. First things first, for jobs that have previously been triggered by an email, if you look under "Parameters" (e.g. http://localhost:8080/job/Quick%20Test/3/parameters/ ), can you see a list of "pmt_" prefixed variables?
2. If so, is there a "pmt_content" parameter, and does it have any content?
3. If so, can you trying using (ONLY) "echo $pmt_content" in you execute script?
4. If that doesn't work, can you try using Jenkins 1.626 and plugin 1.019 (if you aren't already)?

If you still have no luck, please provide me with anything else that will help me reproduce the issue - Jenkins version, plugin version, operating system, screenshots?

Kind regards,

Nick Grealy

### *\* Updated in reponse to your email **

Take a look at the [Custom Job Parameters](https://github.com/jenkinsci/poll-mailbox-trigger-plugin#custom-job-parameters) documentation for the Poll Mailbox Plugin, I think this does what you want.

If you're locked into the format of your email, I'd recommend using a Groovy script to parse the email content.

Kind regards,

Nick Grealy
